# Generated by Django 3.0.3 on 2020-03-03 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_calendermodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendermodel',
            options={'verbose_name': 'CalenderModel'},
        ),
        migrations.AlterModelOptions(
            name='mealmodel',
            options={'verbose_name': 'MealModel'},
        ),
        migrations.AlterField(
            model_name='mealmodel',
            name='detail',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
