# Generated by Django 3.0.3 on 2020-03-03 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0003_auto_20200303_2215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendermodel',
            options={'verbose_name': 'CalenderModel', 'verbose_name_plural': 'CalenderModel'},
        ),
        migrations.AlterModelOptions(
            name='mealmodel',
            options={'verbose_name': 'MealModel', 'verbose_name_plural': 'MealModel'},
        ),
    ]
