# Generated by Django 3.0.3 on 2020-03-13 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0005_auto_20200303_2244'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=150, unique=True)),
                ('detail', models.TextField()),
            ],
            options={
                'verbose_name': 'NoticeModel',
                'verbose_name_plural': 'NoticeModel',
                'db_table': 'NoticeModel',
            },
        ),
    ]
